version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    image: getmanstudio:latest
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - .:/mediafiles
      - .:/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db