# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getman_studio', '0002_auto_20161125_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u041d\u043e\u0432\u0438\u043d\u0430', 'verbose_name_plural': '\u041d\u043e\u0432\u0438\u043d\u0438'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044f', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u0457'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name': '\u0415\u043b\u0435\u043c\u0435\u043d\u0442 \u0433\u0430\u043b\u0435\u0440\u0435\u0457', 'verbose_name_plural': '\u0415\u043b\u0435\u043c\u0435\u043d\u0442\u0438 \u0433\u0430\u043b\u0435\u0440\u0435\u0457'},
        ),
        migrations.AlterModelOptions(
            name='workshopparallaxitem',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043f\u0430\u0440\u0430\u043b\u043b\u0430\u043a\u0441\u0443', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043f\u0430\u0440\u0430\u043b\u043b\u0430\u043a\u0441\u0443'},
        ),
    ]
