# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getman_studio', '0003_auto_20161127_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_id',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='text_id',
            field=models.SlugField(max_length=15),
        ),
    ]
