# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getman_studio', '0004_auto_20161128_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date',), 'verbose_name': '\u041d\u043e\u0432\u0438\u043d\u0430', 'verbose_name_plural': '\u041d\u043e\u0432\u0438\u043d\u0438'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position',), 'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044f', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u0457'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
