# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getman_studio', '0005_auto_20161202_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ('position',), 'verbose_name': '\u0415\u043b\u0435\u043c\u0435\u043d\u0442 \u0433\u0430\u043b\u0435\u0440\u0435\u0457', 'verbose_name_plural': '\u0415\u043b\u0435\u043c\u0435\u043d\u0442\u0438 \u0433\u0430\u043b\u0435\u0440\u0435\u0457'},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
