# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171203_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='shop/'),
        ),
    ]
